set_property PACKAGE_PIN AE5 [get_ports sys_clk_p]
set_property PACKAGE_PIN AH11 [get_ports sys_rst_n]
set_property PACKAGE_PIN AF10 [get_ports led]
set_property PACKAGE_PIN AC12 [get_ports FAN]
set_property PACKAGE_PIN AD11 [get_ports {key[0]}]
set_property PACKAGE_PIN AD10 [get_ports {key[1]}]
set_property PACKAGE_PIN AB9 [get_ports uart_rxd]
set_property PACKAGE_PIN AB10 [get_ports uart_txd]

set_property IOSTANDARD DIFF_HSTL_I_12 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_HSTL_I_12 [get_ports sys_clk_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports FAN]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

create_clock -period 10.000 -name sys_clk_p -waveform {0.000 5.000} [get_ports sys_clk_p]

